"""partner apps and revenue tracking

Revision ID: 1356eb3d81f9
Revises: c6a5938e9d05
Create Date: 2026-09-09 13:13:18.466169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1356eb3d81f9'
down_revision: Union[str, None] = 'c6a5938e9d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnerapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_application_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'active', 'suspended', 'rejected', name='appstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_application_id'], ['partnerapplication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenueentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_app_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_app_id'], ['partnerapp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revenueentry')
    op.drop_table('partnerapp')
    # ### end Alembic commands ###
