"""initial schema

Revision ID: 1c3da842f3bc
Revises: 
Create Date: 2026-09-07 23:15:32.849480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c3da842f3bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otpcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', name='otpchannel'), nullable=False),
    sa.Column('purpose', sa.Enum('register', 'login', 'reset_password', name='otppurpose'), nullable=False),
    sa.Column('hashed_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otpcode_identifier'), 'otpcode', ['identifier'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('partner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'partner', 'client', name='userrole'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_table('partnerapplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='partnerstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bustrip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_application_id', sa.Integer(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('departure_at', sa.DateTime(), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_application_id'], ['partnerapplication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_application_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('awaiting_signature', 'signed', name='contractstatus'), nullable=False),
    sa.Column('signed_by_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_application_id'], ['partnerapplication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('partner_application_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('received', 'in_transit', 'available', 'picked_up', name='parcelstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_generated_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_application_id'], ['partnerapplication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_client_generated_id'), 'parcel', ['client_generated_id'], unique=False)
    op.create_index(op.f('ix_parcel_reference_code'), 'parcel', ['reference_code'], unique=True)
    op.create_table('partneractivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_application_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('contract', 'parcel', 'booking', 'ticket', 'system', name='activitycategory'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_application_id'], ['partnerapplication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_application_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('available', 'occupied', name='roomstatus'), nullable=False),
    sa.ForeignKeyConstraint(['partner_application_id'], ['partnerapplication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('busticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('passenger_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('reserved', 'paid', 'used', name='busticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_generated_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['bustrip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_busticket_client_generated_id'), 'busticket', ['client_generated_id'], unique=False)
    op.create_index(op.f('ix_busticket_reference_code'), 'busticket', ['reference_code'], unique=True)
    op.create_table('roombooking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_generated_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roombooking_client_generated_id'), 'roombooking', ['client_generated_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roombooking_client_generated_id'), table_name='roombooking')
    op.drop_table('roombooking')
    op.drop_index(op.f('ix_busticket_reference_code'), table_name='busticket')
    op.drop_index(op.f('ix_busticket_client_generated_id'), table_name='busticket')
    op.drop_table('busticket')
    op.drop_table('room')
    op.drop_table('partneractivity')
    op.drop_index(op.f('ix_parcel_reference_code'), table_name='parcel')
    op.drop_index(op.f('ix_parcel_client_generated_id'), table_name='parcel')
    op.drop_table('parcel')
    op.drop_table('contract')
    op.drop_table('bustrip')
    op.drop_table('partnerapplication')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_index(op.f('ix_otpcode_identifier'), table_name='otpcode')
    op.drop_table('otpcode')
    op.drop_table('course')
    op.drop_table('contactmessage')
    # ### end Alembic commands ###
